### ISSUE TITLE
1. Jumping will negate the attack of the AI.

### ISSUE THREAD

**Issue by mattys-gay-friend** [ElementalsTest/ElementalsTest.github.io#1]
• Type of Bug: In-Game bug

• Description: If you jump during the attack animation, you will not take damage.

• Steps to reproduce: Let the AI attack you, then jump.

• Expected result: You'll take damage as you're still close to them.

• Observed result: You don't take damage.

• Reproduction rate: 10/10 tries.

**Comment by Muirey03** [comment]
Fixed
