### ISSUE TITLE
2. Hardman is a hard ting, remove him and shitman (waterman) right now

### ISSUE THREAD

**Issue by mattys-gay-friend** [ElementalsTest/ElementalsTest.github.io#2]
• Type of Bug: In-Game bug

• Description: If Hardman jumps and uses his ability on top of the AI, he will be unable to move and float for a couple seconds.

• Steps to reproduce: Jump over the AI and use your ability.

• Expected result: You use your ability.

• Observed result: You get suspended in mid-air because the AI runs underneath you and keep bouncing you back up.

• Reproduction rate: 10/10 tries.

**Comment by ElementalsTest** [comment]
When you say: "unable to move and float for a couple seconds", do you mean literally suspended mid-air, not moving at all? Could you provide a screen recording please?

**Comment by Muirey03** [comment]
Fixed - You should not be able to bounce on his head any more than 2 times now.
