### ISSUE TITLE
3. Elementals is a shit game, but here are some bugs because you're a horny lad

### ISSUE THREAD

**Issue by mattys-gay-friend** [ElementalsTest/ElementalsTest.github.io#3]
• Type of Bug: In-Game bug

• Description: If you stand far-away enough, shit man can attack without pulling aggro.

• Steps to reproduce: Pull the AI into the tunnel and die. Respawn as shit man and attack them.

• Expected result: They start chasing you like white cops chase young black men.

• Observed result: They don't start chasing you like Bill Cosby's women (because they're drugged)

• Reproduction rate: 10/10 tries.

**Comment by Muirey03** [comment]
Fixed
